name: movies_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_rating_bar: ^4.0.1
  get_it: ^8.2.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  readmore: ^3.0.0
  shimmer: ^3.0.0
  stream_transform: ^2.1.0
  url_launcher: ^6.1.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - .env
